exclude: [
  'node_modules/**',
  'src/style/webfontkit-20141208-130438/**',
  'src/style/partials/_reset.scss',
  'src/style/partials/_colorbox.scss',
  'src/style/vendor/**'
]

linters:
  PropertySortOrder:
    enabled: false
  ZeroUnit:
    enabled: false
  LeadingZero:
    enabled: false
  QualifyingElement:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
